version: "3"
services:
  php:
    image: php:8.1.2-fpm-buster
    volumes:
      - ./backend:/app
    working_dir: /app
    command: "php -S localhost:8080"
    network_mode: "host"
  node:
    image: node:16-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c 'yarn install && yarn dev'
    network_mode: "host"
